### ISSUE TITLE
Major refactor of the Angular app

### ISSUE THREAD

**Issue by vitale232** [vitale232/InspectionPlanner#39]
The Angular app needs major reorganization. Now that we've prototyped some components, I'm thinking that we should use the following:
1. OpenLayers for the Map
2. nGrid for the attribute table
3. Angular Splitter for the screen split
4. Angular Material for general components
5. Leaflet MarkerCluster as another visualization option

Also, the Browse feature would be greatly enhanced by also presenting a table, making the layout identical to the DriveTime feature. This means that it would be best to build the map and table components in a reusable way.

I'm thinking a reasonable model for the refactoring is as follows:
1. Use a service to store the bridges. There will be 2; one for all bridges (think "browse" bridges) and one for drive time bridges
    - Think of these as data stores
   - Use a private `BehaviorSubject` to store the bridges
   - Expose the `BehaviorSubject` as an observable for the components
   - Write setters and getters for the `BehaviorSubject` (consider adding caching logic here for browse?)
2. `BrowseBridgesModule`, `DriveTimeModule`, and `SearchModule` will be the initial feature modules of the app.
3. Each module will contain a `DisplayComponent` that will pass the data into the map and table then put the map and table into a splitter. `SearchModule` is the exception; it will contain form components.
3. The router can point to the `DisplayComponents` (e.g. '/' and '/drive-time/518')
4. `LeafletMarkerClusterModule` would be nice to have. It could be an advanced visualization option, and leaflet could be lazy loaded. The first release of this would not support a table.

The shared `OpenLayersMapComponent` could eventually be updated to include advanced visualization options. It would likely be a div that gets inserted above the map with various checkboxes and dropdowns.

A reasonable folder structure to support this is as follows:
````yaml
app:
    - modules:
        - browse-bridges:
            - BrowseBridgesDisplayComponent
        - drive-time:
            - DriveTimeDisplayComponent
        - leaflet-marker-cluster:      # lazy
            - MarkerClusterDisplayComponent
        - search:
            - SearchComponent
            - FormComponents

    - shared:
        - components:
            - NavbarComponent
            - NotFoundComponent
            - OpenLayersMapComponent
            - QueryHistoryTable        # Try nGrid first?
            - grid-components:
                - AttributeGridComponent
                - TemplateGridComponent
        - services:
            - BridgeService
            - DriveTimeQueryService
            - LoadingIndicatorService  # We need to make sure this is required
            - SearchService
            - SidenavService           # We need to make sure this is required
        - stores:
            - BrowseBridgeStore
            - DriveTimeBridgeStore
        - models: 
./app-routering.module.ts:
./app.component.html:
./app.component.ts:
./app.module.ts:

````
